// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// * This file should not be edited directly as it is generated by FlutterFire CLI.

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmUIIymBri6lsobtJW9Q-te0El2n5aog4',
    appId: '1:1008858918563:web:527e2e7c07c92f852e5916',
    messagingSenderId: '1008858918563',
    projectId: 'movie-diary-7a7c3',
    authDomain: 'movie-diary-7a7c3.firebaseapp.com',
    storageBucket: 'movie-diary-7a7c3.firebasestorage.app',
    measurementId: 'G-8049E1JQTH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhxh7jBoRO5jXcdJflgHtdQGpu2w_3b-s',
    appId: '1:1008858918563:android:664f0ef51d04706e2e5916',
    messagingSenderId: '1008858918563',
    projectId: 'movie-diary-7a7c3',
    storageBucket: 'movie-diary-7a7c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfb4HFQrVqAF-PjJlYTA6ifKrb5VZEhzw',
    appId: '1:1008858918563:ios:ba549718277223482e5916',
    messagingSenderId: '1008858918563',
    projectId: 'movie-diary-7a7c3',
    storageBucket: 'movie-diary-7a7c3.firebasestorage.app',
    iosBundleId: 'com.example.movieDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfb4HFQrVqAF-PjJlYTA6ifKrb5VZEhzw',
    appId: '1:1008858918563:ios:ba549718277223482e5916',
    messagingSenderId: '1008858918563',
    projectId: 'movie-diary-7a7c3',
    storageBucket: 'movie-diary-7a7c3.firebasestorage.app',
    iosBundleId: 'com.example.movieDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmUIIymBri6lsobtJW9Q-te0El2n5aog4',
    appId: '1:1008858918563:web:97167abcb26806d22e5916',
    messagingSenderId: '1008858918563',
    projectId: 'movie-diary-7a7c3',
    authDomain: 'movie-diary-7a7c3.firebaseapp.com',
    storageBucket: 'movie-diary-7a7c3.firebasestorage.app',
    measurementId: 'G-3PKEZJ4TLY',
  );
}
